baseURL = "https://photoart.vercel.app/"

## baseURL = "https://aleksmn.github.io/photoart/"
languageCode = "en-us"

## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Aleksandrov Photo"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  github = "https://github.com/aleksmn/"
  twitter = "https://twitter.com/alexandrovphoto/"
  email = "al-mn@yandex.ru"
  instagram = "https://www.instagram.com/alexandrovphotography/"

[Params.footer]
  copy = "Mikhail Aleksandrov, 2021"